---
abstract: 'A version of the undefined object (null object) pattern'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Patterns-UndefObject
requires:
  Sub::Exporter: 0
version: 0.001
