---
abstract: 'A version of the undefined object (null object) pattern'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Patterns-UndefObject
requires:
  Scalar::List::Utils: 0
  Sub::Exporter: 0
resources:
  bugtracker: https://github.com/jjn1056/Patterns-UndefObject/issues
  homepage: https://github.com/jjn1056/Patterns-UndefObject
  repository: https://github.com/jjn1056/Patterns-UndefObject.git
version: 0.003
